backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: settings
    label: Settings
    delete: false
    files:
      - label: "Schedule"
        name: schedule
        file: "src/data/schedule.json"
        identifier_field: date
        widget: list
        fields:
          - { label: "Date", name: "date", format: "MM/DD", widget: "date" }
          - { label: "Morning", name: "morning", widget: "string" }
          - { label: "Afternoon", name: "afternoon", widget: "string" }
          - { label: "Evening", name: "evening", widget: "string" }
      - label: "Speakers"
        name: speakers
        file: "src/data/speakers.json"
        identifier_field: name
        widget: list
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Avatar", name: "avatarUrl", widget: "image" }
